/**
 * OpenAPI contract types — re-exports from the auto-generated spec
 * with semantic aliases for the wire-format types used by plan-wire.ts
 * and submit.ts.
 *
 * Generated by `bun run generate-types` from tastile-core OpenAPI.
 * DO NOT EDIT MANUALLY — aliases only; types come from openapi-generated.d.ts.
 *
 * These types describe the **wire format** (snake_case, externally-tagged
 * enums). The store types (src/lib/domain/v1/*.ts) use camelCase and
 * internally-tagged enums — plan-wire.ts bridges them.
 */

import type { components } from "./openapi-generated";

// ---------------------------------------------------------------
// Plan wire types
// ---------------------------------------------------------------

/** Wire shape for `POST /v1/tiles/{tileId}/plan` body. */
type WirePlan = components["schemas"]["SchedulePlanDefinitionSchema"];

/** Wire shape for Completion (root + time_requirements + tasks). */
export type WireCompletion = components["schemas"]["CompletionSchema"];

/** Wire shape for TaskDefinition. */
export type WireTaskDefinition = components["schemas"]["TaskDefinitionSchema"];

/** Wire shape for TaskContent. */
type WireTaskContent = components["schemas"]["TaskContentSchema"];

/** Wire shape for TaskOrderRule. */
export type WireTaskOrderRule = components["schemas"]["TaskOrderRuleSchema"];

/** Wire shape for TimeRequirement. */
type WireTimeRequirement = components["schemas"]["TimeRequirementSchema"];

// ---------------------------------------------------------------
// Condition / Term wire types
// ---------------------------------------------------------------

/** Wire shape for Condition (externally-tagged: All | Any | Not | Term). */
export type WireCondition = components["schemas"]["ConditionSchema"];

/** Wire shape for Term (externally-tagged: Calendar | Moment | ... | Life). */
export type WireTerm = components["schemas"]["TermSchema"];

/** Wire shape for CalendarTerm. */
export type WireCalendarTerm = components["schemas"]["CalendarTermSchema"];

/** Wire shape for TaskTerm. */
type WireTaskTerm = components["schemas"]["TaskTermSchema"];

// ---------------------------------------------------------------
// Planning wire types
// ---------------------------------------------------------------

/** Wire shape for Planning definition. */
export type WirePlanning = components["schemas"]["SchedulePlanningDefinitionSchema"];

/** Wire shape for PlacementRule. */
type WirePlacementRule = components["schemas"]["PlacementRuleSchema"];

/** Wire shape for NestingRule. */
type WireNestingRule = components["schemas"]["NestingRuleSchema"];

// ---------------------------------------------------------------
// Recurring / Schedule wire types
// ---------------------------------------------------------------

/** Wire shape for SourceGeneration. */
type WireSourceGeneration = components["schemas"]["SourceGenerationSchema"];

/** Wire shape for FlowDefinition (used by schedule creation). */
type WireFlowDefinition = components["schemas"]["FlowDefinitionSchema"];

// ---------------------------------------------------------------
// Primitive wire types
// ---------------------------------------------------------------

/** Wire shape for DateRange (start/end as date strings). */
type WireDateRange = components["schemas"]["DateRangeSchema"];

/** Wire shape for Span. */
type WireSpan = components["schemas"]["SpanSchema"];

/** Wire shape for TimeOfDay. */
type WireTimeOfDay = components["schemas"]["TimeOfDaySchema"];
