# syntax=docker/dockerfile:1.7
# Tastile web — multi-stage build: oven/bun (build) → node:20-bookworm-slim (run).
# next.config.ts uses `output: "standalone"`, so the runtime image only needs
# the standalone bundle, .next/static, and public/.

# ----- build stage -----
FROM oven/bun:1.3.14 AS build
WORKDIR /app
ARG TASTILE_INFISICAL_INJECTED
ARG NEXT_PUBLIC_E2E_BYPASS_AUTH=0
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APEX_HOST
ARG NEXT_PUBLIC_APP_HOST
ARG NEXT_PUBLIC_COGNITO_CALLBACK_URL
ARG NEXT_PUBLIC_COGNITO_CLIENT_ID
ARG NEXT_PUBLIC_COGNITO_ENABLED_PROVIDERS
ARG NEXT_PUBLIC_COGNITO_HOSTED_UI_DOMAIN
ARG NEXT_PUBLIC_COGNITO_ISSUER
ARG NEXT_PUBLIC_COGNITO_JWKS_URL
ARG NEXT_PUBLIC_COGNITO_LOGOUT_URL
ARG NEXT_PUBLIC_COGNITO_REGION
ARG NEXT_PUBLIC_COGNITO_USER_POOL_ID
ARG NEXT_PUBLIC_DAEMON_BASE_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_E2E_BYPASS_AUTH=$NEXT_PUBLIC_E2E_BYPASS_AUTH
ENV TASTILE_INFISICAL_INJECTED=$TASTILE_INFISICAL_INJECTED
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_APEX_HOST=$NEXT_PUBLIC_APEX_HOST \
    NEXT_PUBLIC_APP_HOST=$NEXT_PUBLIC_APP_HOST \
    NEXT_PUBLIC_COGNITO_CALLBACK_URL=$NEXT_PUBLIC_COGNITO_CALLBACK_URL \
    NEXT_PUBLIC_COGNITO_CLIENT_ID=$NEXT_PUBLIC_COGNITO_CLIENT_ID \
    NEXT_PUBLIC_COGNITO_ENABLED_PROVIDERS=$NEXT_PUBLIC_COGNITO_ENABLED_PROVIDERS \
    NEXT_PUBLIC_COGNITO_HOSTED_UI_DOMAIN=$NEXT_PUBLIC_COGNITO_HOSTED_UI_DOMAIN \
    NEXT_PUBLIC_COGNITO_ISSUER=$NEXT_PUBLIC_COGNITO_ISSUER \
    NEXT_PUBLIC_COGNITO_JWKS_URL=$NEXT_PUBLIC_COGNITO_JWKS_URL \
    NEXT_PUBLIC_COGNITO_LOGOUT_URL=$NEXT_PUBLIC_COGNITO_LOGOUT_URL \
    NEXT_PUBLIC_COGNITO_REGION=$NEXT_PUBLIC_COGNITO_REGION \
    NEXT_PUBLIC_COGNITO_USER_POOL_ID=$NEXT_PUBLIC_COGNITO_USER_POOL_ID \
    NEXT_PUBLIC_DAEMON_BASE_URL=$NEXT_PUBLIC_DAEMON_BASE_URL \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

# Install deps first for better layer caching
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Build standalone output
COPY . .
RUN test "$TASTILE_INFISICAL_INJECTED" = "1" && bun run build:prod

# ----- run stage -----
FROM node:20-bookworm-slim AS run
WORKDIR /app

ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Next standalone bundles the minimal server; copy public + static
# separately (next.config.ts does not auto-trace them).
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
