/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/executions/{id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a fact row to an execution (v1/02 §Execution). */
        post: operations["record_execution_fact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finish_execution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pause_execution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resume_execution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/executions/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a task-run row to an execution (v1/02 §Execution). */
        post: operations["mark_execution_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/placements/{id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_execution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans/{id}/completion-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest derived completion state for a Plan (v1/13). */
        get: operations["read_plan_completion_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["request_prompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pending_prompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/startup-recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respond_startup_recovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolve_prompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/schedule-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish_schedule_definition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explicit user close of an open decision Session.  Terminal: feedback
         *     application rejects closed sessions and delivery retries stop.
         */
        post: operations["close_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-tiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SourceTiles owned by the authenticated or queried owner. */
        get: operations["list_source_tiles"];
        put?: never;
        /** Create a new SourceTile.  Server owns all aggregate ids. */
        post: operations["create_source_tile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-tiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one SourceTile plus its occurrences and placements. */
        get: operations["get_source_tile"];
        /**
         * Replace the SourceTile schedule, occurrence set, and revision.
         *     Preserves historical occurrences/placement identity; advances
         *     the SourceTile revision.
         */
        put: operations["update_source_tile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-tiles/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a SourceTile. Transitions the source from ACTIVE to
         *     CANCELLED, emits a `v1_source_lifecycle_event` row, and closes
         *     every source-managed (`source.kind = 4`) Placement whose span
         *     overlaps the source's effective horizon. Running executions on
         *     the closed placements finish naturally; new work cannot be
         *     dispatched against them. Idempotent on retry.
         */
        post: operations["cancel_source_tile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-tiles/{id}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Derive per-segment and whole-occurrence completion for a SourceTile. */
        get: operations["get_source_tile_completion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-tiles/{id}/placements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List canonical Placement rows for a SourceTile in owner scope. */
        get: operations["list_source_tile_placements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/source-tiles/{id}/reflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-evaluate the SourceTile within a window.  Closes affected
         *     auto-managed future placements and emits replacements without
         *     touching detached / execution / placement-override rows.
         */
        post: operations["reflow_source_tile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tiles (v1 view-model projection).  Per
         *     docs/superpowers/plans/2026-07-07-v1-tile-list-view-model.md Task 3
         *     the handler projects `domain::TileListView` so every Tile parameter is
         *     reachable through the API surface (v1/14 §9).
         */
        get: operations["list_tiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AggregateExprSchema: {
            /**
             * Format: int32
             * @description Numeric AggregateFn/TimeScope/TimeSource registry values.
             */
            kind: number;
            /** Format: int32 */
            quantifier?: number | null;
            /** Format: uuid */
            reference?: string | null;
            /** Format: int32 */
            scope: number;
            /** Format: int32 */
            source: number;
        };
        AggregateMetaSchema: {
            change_ids: string[];
            /** Format: uuid */
            changeset_id?: string | null;
            flow_ids: string[];
            /** Format: uuid */
            frame_rule_id?: string | null;
            occurrence_ids: string[];
            placement_ids: string[];
            /** Format: uuid */
            plan_id?: string | null;
            /**
             * Format: uuid
             * @description Id of a Prompt created by `RequestPrompt`.  A Prompt is not an
             *     Aggregate, so it has no `AggregateRef` and no revision; this is the
             *     only place its id is returned (v1/14 §13-2).
             */
            prompt_id?: string | null;
            /** Format: uuid */
            recurring_id?: string | null;
            /** Format: uuid */
            source_tile_id?: string | null;
            /** Format: uuid */
            tile_id?: string | null;
            window_ids: string[];
        };
        AggregateRefSchema: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            kind: number;
        };
        AnchorSelectorSchema: {
            pick: components["schemas"]["PickSchema"];
            when: components["schemas"]["ConditionRefSchema"];
        };
        CalendarTermSchema: {
            date_range?: null | components["schemas"]["DateRangeSchema"];
            /**
             * Format: int32
             * @description Numeric `HolidayKind` registry value.
             */
            holiday_kind: number;
            /**
             * Format: int32
             * @description Fixed offset override; omitted/null inherits the owner timezone.
             *     Zero explicitly selects UTC.
             */
            offset_min?: number | null;
            time_end?: null | components["schemas"]["TimeOfDaySchema"];
            time_start?: null | components["schemas"]["TimeOfDaySchema"];
            /** Format: int32 */
            weekday_mask: number;
        };
        CancelSourceTilePayloadSchema: {
            /**
             * Format: int32
             * @description Numeric cancel reason. See `domain::source_tile::state::cancel_reason`
             *     for the registry values.
             */
            reason: number;
        };
        CancelSourceTileRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["CancelSourceTilePayloadSchema"];
        };
        CandidateEffectSchema: {
            change?: null | components["schemas"]["ChangeRuleSchema"];
            /** Format: uuid */
            idempotency_key?: string | null;
            /**
             * Format: int32
             * @description Numeric `CandidateEffectKind` registry value.
             */
            kind: number;
            proposal?: null | components["schemas"]["PlacementProposalDraftSchema"];
            request?: null | components["schemas"]["RequestDraftSchema"];
        };
        ChangeKeySchema: {
            /**
             * Format: int32
             * @description Numeric `ChangeGroup` registry value.
             */
            group: number;
            /** Format: uuid */
            item?: string | null;
            /** Format: int32 */
            part: number;
        };
        ChangeRuleSchema: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["ChangeKeySchema"];
            /**
             * Format: int32
             * @description Numeric `ChangeKind` registry value.
             */
            kind: number;
            /** Format: int32 */
            rank: number;
            /**
             * Format: int32
             * @description Numeric `ChangeSource` registry value.
             */
            source: number;
            source_ref?: null | components["schemas"]["ChangeSourceRefSchema"];
            target: components["schemas"]["TargetRefSchema"];
            value?: null | components["schemas"]["ChangeValueSchema"];
        };
        ChangeSourceRefSchema: {
            /** Format: uuid */
            decision_run?: string | null;
            /** Format: uuid */
            execution?: string | null;
            /** Format: uuid */
            feedback_txn?: string | null;
            /** Format: uuid */
            flow?: string | null;
            /** Format: uuid */
            frame?: string | null;
            /** Format: uuid */
            recurring?: string | null;
        };
        ChangeValueSchema: {
            Span: components["schemas"]["SpanSchema"];
        } | {
            /** Format: date-time */
            Instant: string;
        } | {
            /** Format: int64 */
            Integer: number;
        } | {
            Text: string;
        } | {
            /** Format: uuid */
            Identifier: string;
        } | {
            Inside: components["schemas"]["InsideSchema"];
        } | {
            RangeInteger: components["schemas"]["RangeI64Schema"];
        } | {
            RangeInstant: components["schemas"]["RangeInstantSchema"];
        } | {
            Bool: boolean;
        } | {
            /** Format: uuid */
            TimeRequirementRef: string;
        } | {
            /** Format: uuid */
            TaskDefRef: string;
        } | "None";
        ChooseBranchSchema: {
            then: components["schemas"]["ScalarExpressionRefSchema"];
            when: components["schemas"]["ConditionRefSchema"];
        };
        ChooseExprSchema: {
            branches: components["schemas"]["ChooseBranchSchema"][];
            default?: null | components["schemas"]["ScalarExpressionRefSchema"];
        };
        CommandResponse: {
            /** Format: date-time */
            accepted_at: string;
            aggregate?: null | components["schemas"]["AggregateRefSchema"];
            aggregate_meta?: null | components["schemas"]["AggregateMetaSchema"];
            /** Format: uuid */
            command_id: string;
            pending: components["schemas"]["PendingWorkSchema"][];
            /**
             * Format: int32
             * @description 0 = applied, 1 = already applied, 2 = accepted.
             */
            result: number;
            /** Format: int64 */
            revision?: number | null;
        };
        CompanionProposalDefinitionSchema: {
            /** Format: uuid */
            proposal_key: string;
            /** Format: int32 */
            relation_kind: number;
            span: components["schemas"]["SpanSchema"];
            /** Format: uuid */
            target_plan_id: string;
        };
        /** @description View-only mirror of `domain::read::CompletionResultView`. */
        CompletionResultViewSchema: {
            /** Format: date-time */
            evaluated_at: string;
            met: boolean;
            /** Format: uuid */
            plan_id: string;
            /** Format: uuid */
            result_id: string;
            terms: components["schemas"]["CompletionTermResultSchema"][];
            /** Format: uuid */
            trigger_id: string;
            /**
             * Format: int32
             * @description 0 = EXECUTION_FINISHED, 1 = FEEDBACK_APPLIED, 2 = DECISION_AUTO_APPLIED
             */
            trigger_kind: number;
        };
        CompletionSchema: {
            root: components["schemas"]["ConditionSchema"];
            tasks: components["schemas"]["TaskDefinitionSchema"][];
            time_requirements: components["schemas"]["TimeRequirementSchema"][];
        };
        /** @description View-only mirror of `domain::read::CompletionTermResultView`. */
        CompletionTermResultSchema: {
            detail?: string | null;
            met: boolean;
            /** Format: int32 */
            position_no: number;
            /** Format: int32 */
            term_kind: number;
        };
        ConditionRefSchema: components["schemas"]["ConditionSchema"];
        ConditionSchema: {
            All: components["schemas"]["ConditionRefSchema"][];
        } | {
            Any: components["schemas"]["ConditionRefSchema"][];
        } | {
            Not: components["schemas"]["ConditionRefSchema"];
        } | {
            Term: components["schemas"]["TermSchema"];
        };
        CreateSourceTilePayloadSchema: {
            flows: components["schemas"]["FlowDefinitionSchema"][];
            horizon: components["schemas"]["SpanSchema"];
            plan: components["schemas"]["SchedulePlanDefinitionSchema"];
            relations?: components["schemas"]["SourceRelationDefinitionPayloadSchema"][] | null;
            schedule: components["schemas"]["SourceScheduleDefinitionSchema"];
            /** Format: uuid */
            source_client_local_id?: string | null;
            tile: components["schemas"]["ScheduleTileDefinitionSchema"];
        };
        CreateSourceTileRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["CreateSourceTilePayloadSchema"];
        };
        DateRangeSchema: {
            /** Format: date */
            end: string;
            /** Format: date */
            start: string;
        };
        DecisionCandidateSchema: {
            effects: components["schemas"]["CandidateEffectSchema"][];
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            rank: number;
            when: components["schemas"]["ConditionRefSchema"];
        };
        DecisionDefSchema: {
            candidates: components["schemas"]["DecisionCandidateSchema"][];
            dialog: components["schemas"]["InteractionNodeSchema"];
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description Numeric `DecisionObserve` registry value.
             */
            observe: number;
            reuse: components["schemas"]["FeedbackReuseRuleSchema"][];
            when?: null | components["schemas"]["ConditionRefSchema"];
        };
        /** @description Placeholder for a command whose payload carries no fields. */
        EmptyPayloadSchema: Record<string, never>;
        /**
         * @description `PAUSE_EXECUTION` / `RESUME_EXECUTION` take no payload of their own —
         *     the execution id comes from the path, so the wire value of `payload`
         *     is `null` (`CommandRequest<()>`).
         */
        ExecutionLifecycleRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload?: null | components["schemas"]["EmptyPayloadSchema"];
        };
        FactComparisonSchema: {
            Equal: string;
        } | {
            NotEqual: string;
        } | {
            /** Format: int64 */
            GreaterThan: number;
        } | {
            /** Format: int64 */
            LessThan: number;
        } | {
            InRange: components["schemas"]["RangeI64Schema"];
        } | "Exists" | "Missing";
        FactTermSchema: {
            comparison: components["schemas"]["FactComparisonSchema"];
            key: string;
        };
        FeedbackMappingSchema: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["ChangeKeySchema"];
            /**
             * Format: int32
             * @description Numeric `ChangeKind` registry value.
             */
            kind: number;
            target: components["schemas"]["TargetRefSchema"];
            value?: null | components["schemas"]["ChangeValueSchema"];
        };
        FeedbackReuseRuleSchema: {
            apply: components["schemas"]["FeedbackMappingSchema"][];
            /** Format: uuid */
            id: string;
            source: components["schemas"]["FeedbackSelectorSchema"];
            when: components["schemas"]["ConditionRefSchema"];
        };
        FeedbackSelectorSchema: "All" | {
            /** Format: uuid */
            Feedback: string;
        } | {
            /** Format: int64 */
            Within: number;
        };
        FeedbackTermSchema: {
            /** Format: uuid */
            feedback_txn: string;
            /**
             * Format: int32
             * @description Numeric `FeedbackState` newtype value.
             */
            state: number;
        };
        FinishExecutionPayloadSchema: {
            /**
             * Format: int32
             * @description Numeric finish kind (v1/02 §Execution 終了情報). Opaque smallint
             *     until the v1.1 registry publishes the values.
             */
            kind: number;
            note?: string | null;
        };
        FinishExecutionRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["FinishExecutionPayloadSchema"];
        };
        FlowDefinitionSchema: {
            candidates: components["schemas"]["ScheduleFlowCandidateDefinitionSchema"][];
            observes: components["schemas"]["ScheduleFlowSignalSchema"][];
            when?: null | components["schemas"]["ConditionRefSchema"];
        };
        GapAnchorsSchema: {
            left: components["schemas"]["AnchorSelectorSchema"];
            right: components["schemas"]["AnchorSelectorSchema"];
            size?: null | components["schemas"]["RangeI64Schema"];
        };
        GapTermSchema: {
            left_anchor: components["schemas"]["AnchorSelectorSchema"];
            right_anchor: components["schemas"]["AnchorSelectorSchema"];
            scope: components["schemas"]["ScopeSchema"];
            size?: null | components["schemas"]["RangeI64Schema"];
        };
        InsideSchema: {
            /** Format: uuid */
            parent: string;
            /**
             * Format: int32
             * @description Numeric `ScopeKind` registry value.
             */
            scope: number;
        };
        InteractionInputSchema: {
            /**
             * Format: int32
             * @description Numeric `InputAcceptance` registry value.
             */
            acceptance: number;
            current: components["schemas"]["ChangeValueSchema"][];
            enabled?: null | components["schemas"]["ConditionRefSchema"];
            /** Format: uuid */
            id: string;
            options: components["schemas"]["InteractionOptionSchema"][];
            visible?: null | components["schemas"]["ConditionRefSchema"];
        };
        InteractionNodeRefSchema: components["schemas"]["InteractionNodeSchema"];
        InteractionNodeSchema: {
            children: components["schemas"]["InteractionNodeRefSchema"][];
            /** Format: uuid */
            id: string;
            inputs: components["schemas"]["InteractionInputSchema"][];
            view: components["schemas"]["InteractionViewSchema"];
            visible?: null | components["schemas"]["ConditionRefSchema"];
        };
        InteractionOptionSchema: {
            /** Format: uuid */
            id: string;
            label: string;
            value: components["schemas"]["ChangeValueSchema"];
        };
        InteractionViewSchema: {
            body?: string | null;
            title: string;
        };
        /** @enum {string} */
        LifeStateSchema: "Active" | "Paused" | "Closed" | "Voided";
        LifeTargetSchema: {
            /** Format: uuid */
            Tile: string;
        } | {
            /** Format: uuid */
            Placement: string;
        } | {
            /** Format: uuid */
            Execution: string;
        } | {
            /** Format: uuid */
            Recurring: string;
        };
        LifeTermSchema: {
            state: components["schemas"]["LifeStateSchema"];
            target: components["schemas"]["LifeTargetSchema"];
        };
        MarkExecutionTaskPayloadSchema: {
            /**
             * Format: int32
             * @description TaskStateKind registry value (0 Visible / 1 Marked / 2 Completed / 3 NotCompleted).
             */
            state: number;
            /** Format: uuid */
            task_id: string;
        };
        /** @description `POST /v1/executions/{id}/tasks` body. */
        MarkExecutionTaskRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["MarkExecutionTaskPayloadSchema"];
        };
        MetricComparisonSchema: {
            /** Format: int64 */
            Equal: number;
        } | {
            /** Format: int64 */
            NotEqual: number;
        } | {
            /** Format: int64 */
            GreaterThan: number;
        } | {
            /** Format: int64 */
            LessThan: number;
        } | {
            InRange: components["schemas"]["RangeI64Schema"];
        } | "Exists" | "Missing";
        MetricDefSchema: {
            expression: components["schemas"]["ScalarExpressionSchema"];
            /** Format: uuid */
            id: string;
            limit?: null | components["schemas"]["RangeI64Schema"];
            /**
             * Format: int32
             * @description Numeric `MetricOutput` registry value.
             */
            output: number;
        };
        MetricTermSchema: {
            comparison: components["schemas"]["MetricComparisonSchema"];
            /** Format: uuid */
            metric_id: string;
        };
        MomentComparisonSchema: {
            /** Format: date-time */
            At: string;
        } | {
            Before: components["schemas"]["MomentTargetSchema"];
        } | {
            After: components["schemas"]["MomentTargetSchema"];
        } | {
            /** @description Exactly two targets on the serde wire. */
            Between: components["schemas"]["MomentTargetSchema"][];
        } | {
            Within: components["schemas"]["RangeI64Schema"];
        };
        MomentSchema: {
            /** Format: date-time */
            Absolute: string;
        } | {
            Reference: Record<string, never>[];
        };
        MomentTargetSchema: {
            /** Format: int32 */
            Context: number;
        } | {
            /** Format: uuid */
            Reference: string;
        } | {
            /** Format: uuid */
            Placement: string;
        } | {
            /** Format: uuid */
            Execution: string;
        } | {
            /** Format: uuid */
            Frame: string;
        };
        MomentTermSchema: {
            comparison: components["schemas"]["MomentComparisonSchema"];
            /** Format: int64 */
            offset: number;
            /**
             * Format: int32
             * @description Numeric `PointReference` registry value.
             */
            point: number;
            target: components["schemas"]["MomentTargetSchema"];
        };
        NestingRuleSchema: {
            /**
             * Format: int32
             * @description Numeric `NestingDirection` registry value.
             */
            direction: number;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            rank: number;
            scope: components["schemas"]["ScopeSchema"];
            target: components["schemas"]["ReferenceSchema"];
            when?: null | components["schemas"]["ConditionRefSchema"];
        };
        NewPlanProposalDefinitionSchema: {
            span: components["schemas"]["SpanSchema"];
        };
        OperateExprSchema: {
            /**
             * Format: int32
             * @description Numeric `OperateKind` registry value.
             */
            op: number;
            operands: components["schemas"]["ScalarExpressionRefSchema"][];
        };
        OutputSequenceStepSchema: {
            /** Format: int64 */
            emit_duration_ms: number;
            /**
             * Format: uuid
             * @description Optional per-step Plan target; omitted steps inherit the output proposal Plan.
             */
            target_plan_id?: string | null;
            /** Format: int64 */
            wait_before_ms: number;
        };
        PendingWorkSchema: {
            /** Format: date-time */
            expected_at?: string | null;
            /** Format: int32 */
            kind: number;
            /** Format: uuid */
            work_item_id: string;
        };
        PickSchema: {
            at?: null | components["schemas"]["MomentSchema"];
            /**
             * Format: int32
             * @description Numeric `PickKind` registry value.
             */
            kind: number;
        };
        PlacementBaselineSchema: {
            inside?: null | components["schemas"]["InsideSchema"];
            span: components["schemas"]["SpanSchema"];
        };
        PlacementProposalDraftSchema: {
            baseline: components["schemas"]["PlacementBaselineSchema"];
            /** Format: uuid */
            id: string;
            inside?: null | components["schemas"]["InsideSchema"];
            /** Format: uuid */
            plan_id: string;
            proposal_key?: null | components["schemas"]["ProposalKeySchema"];
            /** Format: uuid */
            tile_id: string;
        };
        PlacementRuleEffectSchema: {
            /**
             * Format: int32
             * @description Numeric `PlacementRuleEffectKind` registry value.
             */
            kind: number;
            /**
             * Format: int32
             * @description Numeric `RecordRequirement` registry value.
             */
            record?: number | null;
            scope?: null | components["schemas"]["ScopeSchema"];
            /** Format: int32 */
            score?: number | null;
            span?: null | components["schemas"]["RangeI64Schema"];
        };
        PlacementRuleSchema: {
            effect: components["schemas"]["PlacementRuleEffectSchema"];
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            rank: number;
            when?: null | components["schemas"]["ConditionRefSchema"];
        };
        PlacementTileRead: {
            closed: boolean;
            /** Format: date-time */
            closed_at?: string | null;
            /** Format: date-time */
            end: string;
            /** Format: uuid */
            occurrence_id: string;
            /** Format: uuid */
            placement_id: string;
            /** Format: int64 */
            revision: number;
            /** Format: uuid */
            source_tile_id: string;
            /** Format: int32 */
            split_count: number;
            /** Format: uuid */
            split_group_id: string;
            /** Format: int32 */
            split_index: number;
            /** Format: date-time */
            start: string;
        };
        PromptSubjectSchema: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description `AggregateKind` (0 RECURRING / 1 PLACEMENT / 2 EXECUTION / 3 SESSION / 4 SOURCE).
             */
            kind: number;
        };
        PromptView: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description `PromptKind` (v1/14 §13-3).
             */
            kind: number;
            note?: string | null;
            subject?: null | components["schemas"]["PromptSubjectSchema"];
        };
        ProposalKeySchema: {
            /** Format: uuid */
            local_id: string;
            /** Format: uuid */
            producer_id: string;
        };
        PublishScheduleDefinitionPayloadSchema: {
            flows: components["schemas"]["FlowDefinitionSchema"][];
            plan: components["schemas"]["SchedulePlanDefinitionSchema"];
            reference_targets: unknown[];
            relations?: components["schemas"]["SourceRelationDefinitionPayloadSchema"][] | null;
            /** Format: uuid */
            source_client_local_id?: string | null;
            source_horizon?: null | components["schemas"]["SpanSchema"];
            source_schedule?: null | components["schemas"]["SourceScheduleDefinitionSchema"];
            tile: components["schemas"]["ScheduleTileDefinitionSchema"];
            windows: unknown[];
        };
        PublishScheduleDefinitionRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            /** Format: uuid */
            owner_id?: string | null;
            payload: components["schemas"]["PublishScheduleDefinitionPayloadSchema"];
        };
        RangeI64Schema: {
            /** Format: int64 */
            max?: number | null;
            /** Format: int64 */
            min?: number | null;
        };
        RangeInstantSchema: {
            /** Format: date-time */
            max?: string | null;
            /** Format: date-time */
            min?: string | null;
        };
        ReadTargetSchema: {
            /** Format: uuid */
            FrameDuration: string;
        } | {
            /** Format: uuid */
            PlacementSpan: string;
        } | {
            /** Format: uuid */
            ExecutionActiveDuration: string;
        } | {
            Fact: Record<string, never>[];
        } | {
            /** Format: uuid */
            Metric: string;
        } | {
            /** Format: uuid */
            RequirementMet: string;
        } | {
            /** Format: uuid */
            TaskCompleted: string;
        };
        RecordExecutionFactPayloadSchema: {
            fact_key: string;
            fact_value?: string | null;
        };
        /** @description `POST /v1/executions/{id}/facts` body. */
        RecordExecutionFactRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["RecordExecutionFactPayloadSchema"];
        };
        /** @description Recurrence model summary (mirror of `domain::read::RecurrenceView`). */
        RecurrenceView: {
            expression?: string | null;
            /** Format: int32 */
            step_min: number;
            /** Format: int32 */
            window_end_min: number;
            /** Format: int32 */
            window_start_min: number;
        };
        ReferenceDefSchema: {
            /** Format: uuid */
            id: string;
            pick: components["schemas"]["PickSchema"];
            /**
             * Format: int32
             * @description Numeric `TargetSelector` registry value.
             */
            target: number;
            when?: null | components["schemas"]["ConditionRefSchema"];
        };
        ReferenceSchema: {
            /** Format: uuid */
            id: string;
            pick: components["schemas"]["PickSchema"];
            /**
             * Format: int32
             * @description Numeric `TargetSelector` registry value.
             */
            target: number;
        };
        ReflowSourceTilePayloadSchema: {
            range: components["schemas"]["SpanSchema"];
        };
        ReflowSourceTileRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["ReflowSourceTilePayloadSchema"];
        };
        RelationDefinitionRead: {
            /** Format: date-time */
            anchor_at: string;
            /** Format: uuid */
            client_local_id: string;
            /** Format: int32 */
            correlation_scope: number;
            duration: components["schemas"]["RelationDurationExpressionRead"];
            /** Format: int64 */
            eligible_through_revision: number;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            kind: number;
            /** Format: int32 */
            lifecycle_filter: number;
            ordering: components["schemas"]["SelectionOrderingSchema"];
            /** Format: uuid */
            owner_id: string;
            reference: components["schemas"]["RelationPointReferenceRead"];
            /** Format: int64 */
            revision: number;
            /** Format: uuid */
            source_id: string;
            split_policy: components["schemas"]["RelationSplitPolicySchema"];
            /** Format: int32 */
            summary_priority: number;
        };
        RelationDurationExpressionRead: {
            /** Format: int64 */
            Fixed: number;
        } | {
            ReferenceSpan: {
                /** Format: uuid */
                source_id: string;
            };
        };
        RelationPointReferenceRead: {
            /** Format: int64 */
            offset_ms: number;
            /** Format: int32 */
            point: number;
            /** Format: uuid */
            source_id: string;
        };
        RelationSplitPolicySchema: {
            Unsplit: {
                /** Format: int64 */
                required_total_duration_ms: number;
            };
        } | {
            Split: {
                /** Format: int64 */
                max_segment_ms: number;
                /** Format: int64 */
                min_segment_ms: number;
                /** Format: int64 */
                required_total_duration_ms: number;
            };
        };
        RelationTermSchema: {
            /** Format: uuid */
            reference_id: string;
            /**
             * Format: int32
             * @description Numeric `Relation` registry value.
             */
            relation: number;
            /** @description Serde textual `RelationWindowKind` variant. */
            window_kind: components["schemas"]["RelationWindowKindSchema"];
        };
        /** @enum {string} */
        RelationWindowKindSchema: "Root" | "LabelSpan" | "ParentSpan" | "Gap";
        RequestDraftSchema: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            idempotency_key: string;
            kind: components["schemas"]["RequestKindSchema"];
            payload?: null | components["schemas"]["ChangeValueSchema"];
        };
        RequestKindSchema: {
            /** Format: uuid */
            StartExecution: string;
        } | {
            /** Format: uuid */
            FinishExecution: string;
        } | {
            /** Format: uuid */
            PauseExecution: string;
        } | {
            /** Format: uuid */
            ResumeExecution: string;
        } | {
            /** Format: uuid */
            RecordFact: string;
        } | {
            MarkTask: string[];
        };
        RequestPromptPayloadSchema: {
            /** Format: date-time */
            expires_at?: string | null;
            /**
             * Format: int32
             * @description `PromptKind` — 0 STARTUP_RECOVERY / 1 MISSED_START /
             *     2 DECISION_REQUIRED / 3 STALE_ACTIVE_EXECUTION (v1/14 §13-3).
             */
            kind: number;
            note?: string | null;
            subject?: null | components["schemas"]["PromptSubjectSchema"];
        };
        RequestPromptRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            /** Format: uuid */
            owner_id?: string | null;
            payload: components["schemas"]["RequestPromptPayloadSchema"];
        };
        /** @enum {string} */
        RequirementStateSchema: "Met" | "Unmet" | "Any";
        RequirementTermSchema: {
            state: components["schemas"]["RequirementStateSchema"];
            /** Format: uuid */
            time_requirement: string;
        };
        ResolvePromptPayloadSchema: {
            /**
             * Format: int32
             * @description `PromptResolution` — 0 ACKNOWLEDGED / 1 DISMISSED / 2 ACTION_TAKEN.
             */
            resolution: number;
            response_note?: string | null;
        };
        ResolvePromptRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            /** Format: uuid */
            owner_id?: string | null;
            payload: components["schemas"]["ResolvePromptPayloadSchema"];
        };
        ScalarExpressionRefSchema: components["schemas"]["ScalarExpressionSchema"];
        ScalarExpressionSchema: {
            /** Format: int64 */
            Literal: number;
        } | {
            Read: components["schemas"]["ReadTargetSchema"];
        } | {
            Aggregate: components["schemas"]["AggregateExprSchema"];
        } | {
            Operate: components["schemas"]["OperateExprSchema"];
        } | {
            Choose: components["schemas"]["ChooseExprSchema"];
        };
        ScheduleFlowCandidateDefinitionSchema: {
            outputs: components["schemas"]["ScheduleFlowOutputDefinitionSchema"][];
            /** Format: int32 */
            rank: number;
            when: components["schemas"]["ConditionRefSchema"];
        };
        ScheduleFlowOutputDefinitionSchema: {
            ProposeNewPlanPlacement: components["schemas"]["NewPlanProposalDefinitionSchema"];
        } | {
            ProposeNewPlanPlacementSequence: {
                proposal: components["schemas"]["NewPlanProposalDefinitionSchema"];
                sequence_steps: components["schemas"]["OutputSequenceStepSchema"][];
            };
        } | {
            ProposeChangeWithCompanions: {
                change: components["schemas"]["ChangeRuleSchema"];
                /**
                 * Format: int32
                 * @description Optional for legacy clients; omitted values default to Placement (1).
                 */
                change_layer?: number | null;
                companions: components["schemas"]["CompanionProposalDefinitionSchema"][];
            };
        };
        /** @enum {string} */
        ScheduleFlowSignalSchema: "PlacementCreated" | "PlacementUpdated" | "PlacementClosed" | "ExecutionStarted" | "ExecutionFinished" | "FactChanged" | "MetricChanged";
        SchedulePlanDefinitionSchema: {
            completion: components["schemas"]["CompletionSchema"];
            decisions: components["schemas"]["DecisionDefSchema"][];
            metrics: components["schemas"]["MetricDefSchema"][];
            planning: components["schemas"]["SchedulePlanningDefinitionSchema"];
            references: components["schemas"]["ReferenceDefSchema"][];
            /**
             * Format: int32
             * @description Numeric `PlanRole` registry value.
             */
            role: number;
        };
        SchedulePlanningDefinitionSchema: {
            nesting_rules: components["schemas"]["NestingRuleSchema"][];
            placement_rules: components["schemas"]["PlacementRuleSchema"][];
        };
        ScheduleTileDefinitionSchema: {
            color?: string | null;
            description?: string | null;
            external_id?: string | null;
            icon?: string | null;
            title: string;
        };
        ScopeSchema: {
            gap?: null | components["schemas"]["GapAnchorsSchema"];
            /**
             * Format: int32
             * @description Numeric `ScopeKind` registry value.
             */
            kind: number;
            /** Format: uuid */
            parent?: string | null;
        };
        SelectionOrderingSchema: {
            /** Format: int32 */
            direction: number;
            /** Format: int32 */
            point: number;
            /** Format: int32 */
            primary: number;
        };
        SourceGenerationSchema: {
            /** Format: date-time */
            at?: string | null;
            /** @description Exclusive ISO-8601 calendar date upper bound. */
            date_range_end?: string | null;
            /** @description Inclusive ISO-8601 calendar date lower bound. */
            date_range_start?: string | null;
            /** Format: date-time */
            ends_at?: string | null;
            /**
             * @description ISO-8601 calendar dates skipped by this source. Omitted defaults to no exclusions.
             * @default []
             */
            excluded_dates: string[];
            /** Format: int64 */
            interval_ms?: number | null;
            /**
             * Format: int32
             * @description 0 = one-time, 1 = recurring.
             */
            kind: number;
            /**
             * Format: int32
             * @description Explicit local calendar offset in minutes east of UTC (e.g. 540
             *     for Asia/Tokyo).  Omitted means the owner profile timezone
             *     applies; both absent means UTC.
             */
            offset_min?: number | null;
            /** Format: date-time */
            starts_at?: string | null;
            /**
             * Format: int32
             * @description Bitmask for Monday through Sunday; omitted means every weekday.
             */
            weekday_mask?: number | null;
        };
        SourceOccurrenceRead: {
            /** Format: date-time */
            nominal_at: string;
            /** Format: uuid */
            occurrence_id: string;
            /** Format: int64 */
            required_duration_ms: number;
            /** Format: int64 */
            revision: number;
            /** Format: int64 */
            sequence_no: number;
            /** Format: uuid */
            source_tile_id: string;
            /** Format: int32 */
            state: number;
            /** Format: date-time */
            window_end: string;
            /** Format: date-time */
            window_start: string;
        };
        SourceRelationDefinitionPayloadSchema: {
            /** Format: uuid */
            client_local_id: string;
            /** Format: int32 */
            correlation_scope: number;
            duration_expression: components["schemas"]["SourceRelationDurationExpressionSchema"];
            /** Format: int64 */
            eligible_through_revision: number;
            /** Format: int32 */
            kind: number;
            /** Format: int32 */
            lifecycle_filter: number;
            /** Format: int64 */
            offset_ms: number;
            ordering: components["schemas"]["SelectionOrderingSchema"];
            /** Format: int32 */
            point: number;
            /** @description May reference the operation-local source or a same-owner existing source. */
            referenced_source_ref: components["schemas"]["SourceRelationEndpointRefSchema"];
            split_policy: components["schemas"]["RelationSplitPolicySchema"];
            /** @description Must be a local endpoint matching the source alias in this operation. */
            subject_source_ref: components["schemas"]["SourceRelationEndpointRefSchema"];
            /** Format: int32 */
            summary_priority: number;
        };
        SourceRelationDurationExpressionSchema: {
            /** Format: int64 */
            duration_ms: number;
            /** @enum {string} */
            kind: "fixed";
        } | {
            /** @enum {string} */
            kind: "reference_span";
            referenced_source_ref: components["schemas"]["SourceRelationEndpointRefSchema"];
        };
        SourceRelationEndpointRefSchema: {
            /** Format: uuid */
            client_local_id: string;
            /** @enum {string} */
            kind: "local";
        } | {
            /** @enum {string} */
            kind: "existing";
            /** Format: uuid */
            source_tile_id: string;
        };
        SourceScheduleDefinitionSchema: {
            generation: components["schemas"]["SourceGenerationSchema"];
            /** Format: int32 */
            priority: number;
            /** Format: int64 */
            required_duration_ms: number;
            split_policy: components["schemas"]["SplitPolicySchema"];
            window: components["schemas"]["SourceWindowSchema"];
        };
        SourceTileDetailRead: {
            occurrences: components["schemas"]["SourceOccurrenceRead"][];
            placements: components["schemas"]["PlacementTileRead"][];
            relations: components["schemas"]["RelationDefinitionRead"][];
            source: components["schemas"]["SourceTileRead"];
        };
        SourceTileRead: {
            color?: string | null;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            external_id?: string | null;
            icon?: string | null;
            /** Format: uuid */
            owner_id: string;
            /** Format: uuid */
            plan_id: string;
            /** Format: int32 */
            plan_role: number;
            /** Format: int64 */
            revision: number;
            schedule: components["schemas"]["SourceScheduleDefinitionSchema"];
            /**
             * Format: int32
             * @description Numeric SourceTile lifecycle state (0 ACTIVE .. 3 CANCELLED).
             */
            source_state: number;
            /** Format: uuid */
            source_tile_id: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Mirror of `domain::read::SourceTileSummary` for utoipa schema generation. */
        SourceTileSummary: {
            color?: string | null;
            external_id?: string | null;
            /** Format: int32 */
            generation_kind: number;
            icon?: string | null;
            /** Format: int32 */
            priority: number;
            /** Format: int64 */
            required_duration_ms: number;
            /** Format: int32 */
            source_state: number;
            /** Format: int32 */
            split_kind: number;
            /** Format: int32 */
            weekday_mask?: number | null;
            /** Format: int64 */
            window_end_offset_ms: number;
            /** Format: int64 */
            window_start_offset_ms: number;
        };
        SourceWindowSchema: {
            /** Format: int64 */
            end_offset_ms: number;
            /** Format: int64 */
            start_offset_ms: number;
        };
        SpanSchema: {
            /** Format: date-time */
            end: string;
            /** Format: date-time */
            start: string;
        };
        SplitPolicySchema: {
            /**
             * Format: int32
             * @description 0 = unsplit, 1 = split.
             */
            kind: number;
            /** Format: int64 */
            max_segment_ms?: number | null;
            /** Format: int32 */
            max_segments?: number | null;
            /** Format: int64 */
            min_segment_ms?: number | null;
        };
        /**
         * @description `payload` of `START_EXECUTION`.  The placement id also appears in the
         *     path; a mismatch is rejected with VALIDATION.
         */
        StartExecutionPayloadSchema: {
            /** Format: uuid */
            placement_id: string;
        };
        StartExecutionRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            /**
             * Format: uuid
             * @description Optional WORKSPACE owner override; must be owned by the actor.
             */
            owner_id?: string | null;
            payload: components["schemas"]["StartExecutionPayloadSchema"];
        };
        /**
         * @description `POST /v1/prompts/startup-recovery` names the prompt in the body
         *     because it has no path parameter.
         */
        StartupRecoveryPayloadSchema: {
            /** Format: uuid */
            prompt_id: string;
            /**
             * Format: int32
             * @description `PromptResolution` — 0 ACKNOWLEDGED / 1 DISMISSED / 2 ACTION_TAKEN.
             */
            resolution: number;
            response_note?: string | null;
        };
        StartupRecoveryRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            /** Format: uuid */
            owner_id?: string | null;
            payload: components["schemas"]["StartupRecoveryPayloadSchema"];
        };
        TargetRefSchema: {
            /** Format: uuid */
            Placement: string;
        } | {
            /** Format: uuid */
            Execution: string;
        } | {
            /** Format: uuid */
            Plan: string;
        };
        TaskContentSchema: {
            description?: string | null;
            title: string;
        };
        TaskDefinitionSchema: {
            complete: components["schemas"]["ConditionRefSchema"];
            content: components["schemas"]["TaskContentSchema"];
            /** Format: uuid */
            id: string;
            order: components["schemas"]["TaskOrderRuleSchema"][];
            show?: null | components["schemas"]["ConditionRefSchema"];
        };
        TaskOrderRuleSchema: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int32
             * @description Numeric `TaskOrderRelation` registry value.
             */
            relation: number;
            /** Format: uuid */
            target_task_id: string;
            when?: null | components["schemas"]["ConditionRefSchema"];
        };
        /** @enum {string} */
        TaskStateKindSchema: "Visible" | "Marked" | "Completed" | "NotCompleted";
        TaskTermSchema: {
            state: components["schemas"]["TaskStateKindSchema"];
            /** Format: uuid */
            task_id: string;
        };
        /** @description Temporal window for a Tile (mirror of `domain::read::TemporalView`). */
        TemporalView: {
            /** Format: date-time */
            active_end?: string | null;
            /** Format: date-time */
            active_start?: string | null;
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            fixed_end?: string | null;
            /** Format: date-time */
            fixed_start?: string | null;
            /** Format: date-time */
            release_at?: string | null;
        };
        TermSchema: {
            Calendar: components["schemas"]["CalendarTermSchema"];
        } | {
            Moment: components["schemas"]["MomentTermSchema"];
        } | {
            Relation: components["schemas"]["RelationTermSchema"];
        } | {
            Gap: components["schemas"]["GapTermSchema"];
        } | {
            Requirement: components["schemas"]["RequirementTermSchema"];
        } | {
            Task: components["schemas"]["TaskTermSchema"];
        } | {
            Fact: components["schemas"]["FactTermSchema"];
        } | {
            Metric: components["schemas"]["MetricTermSchema"];
        } | {
            Feedback: components["schemas"]["FeedbackTermSchema"];
        } | {
            Life: components["schemas"]["LifeTermSchema"];
        };
        /** @description Rich tile-list view-model (mirror of `domain::read::TileListView`). */
        TileListView: {
            /** Format: int64 */
            break_minutes: number;
            done_definition?: string | null;
            /** Format: int32 */
            done_rule?: number | null;
            /** Format: uuid */
            id: string;
            labels: string[];
            /** Format: int32 */
            lifecycle: number;
            next_action?: string | null;
            /** Format: int32 */
            objective_mode: number;
            /** Format: uuid */
            plan_id?: string | null;
            /** Format: date-time */
            projected_next_start_at?: string | null;
            recurrence?: null | components["schemas"]["RecurrenceView"];
            resume_note?: string | null;
            source?: null | components["schemas"]["SourceTileSummary"];
            /** Format: int32 */
            target_rest_min?: number | null;
            /** Format: int32 */
            target_work_min?: number | null;
            temporal?: null | components["schemas"]["TemporalView"];
            title: string;
            /** Format: int64 */
            worked_minutes: number;
        };
        TimeObservationSchema: {
            /** Format: int32 */
            aggregate: number;
            /** Format: int32 */
            quantifier?: number | null;
            /** Format: uuid */
            reference?: string | null;
            /**
             * Format: int32
             * @description Numeric TimeScope/TimeSource/TimeAggregate registry values.
             */
            scope: number;
            /** Format: int32 */
            source: number;
        };
        TimeOfDaySchema: {
            /** Format: int32 */
            hour: number;
            /** Format: int32 */
            minute: number;
            /** Format: int32 */
            nanos: number;
            /** Format: int32 */
            second: number;
        };
        TimeRequirementSchema: {
            /** Format: uuid */
            id: string;
            observation: components["schemas"]["TimeObservationSchema"];
            preferred?: null | components["schemas"]["RangeI64Schema"];
            required: components["schemas"]["RangeI64Schema"];
        };
        UpdateSourceTilePayloadSchema: {
            flows: components["schemas"]["FlowDefinitionSchema"][];
            horizon: components["schemas"]["SpanSchema"];
            plan: components["schemas"]["SchedulePlanDefinitionSchema"];
            relations?: components["schemas"]["SourceRelationDefinitionPayloadSchema"][] | null;
            schedule: components["schemas"]["SourceScheduleDefinitionSchema"];
            /** Format: uuid */
            source_client_local_id?: string | null;
            tile: components["schemas"]["ScheduleTileDefinitionSchema"];
        };
        UpdateSourceTileRequest: {
            /** Format: int64 */
            expected_revision?: number | null;
            /** Format: uuid */
            idempotency_key: string;
            /** Format: date-time */
            occurred_at?: string | null;
            payload: components["schemas"]["UpdateSourceTilePayloadSchema"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    record_execution_fact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Execution id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordExecutionFactRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error (empty fact key) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution is void */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finish_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Execution id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishExecutionRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pause_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Execution id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionLifecycleRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution is not in a pausable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resume_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Execution id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionLifecycleRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution is not in a resumable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mark_execution_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Execution id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkExecutionTaskRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error (unknown TaskStateKind) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Execution is void */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Placement id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartExecutionRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Path id and payload id do not match */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Placement not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_plan_completion_result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest append-only completion evaluation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResultViewSchema"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown plan, or no completion evaluation yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_prompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPromptRequest"];
            };
        };
        responses: {
            /** @description Command response; the new id is in aggregateMeta.promptId */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error (unknown kind, subject mismatch) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_pending_prompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unresolved, unexpired prompts oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptView"][];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    respond_startup_recovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartupRecoveryRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown prompt, or owned by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Prompt is already resolved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolve_prompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Prompt id */
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePromptRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown prompt, or owned by someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Prompt is already resolved */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publish_schedule_definition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishScheduleDefinitionRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    close_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionLifecycleRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_source_tiles: {
        parameters: {
            query?: {
                /** @description Owner or delegated workspace */
                owner_id?: string;
                /** @description Maximum rows (1..500) */
                limit?: number;
                /** @description Rows to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of SourceTiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTileRead"][];
                };
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_source_tile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description SourceTile command envelope */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceTileRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_source_tile: {
        parameters: {
            query?: {
                /** @description Owner or delegated workspace */
                owner_id?: string;
                /** @description Maximum occurrences and placements (1..500) */
                limit?: number;
                /** @description Occurrences and placements to skip */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description SourceTile id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SourceTile detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTileDetailRead"];
                };
            };
            /** @description Not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_source_tile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SourceTile id */
                id: string;
            };
            cookie?: never;
        };
        /** @description SourceTile update command envelope */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceTileRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_source_tile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SourceTile id */
                id: string;
            };
            cookie?: never;
        };
        /** @description SourceTile cancel command envelope */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelSourceTileRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation error (e.g. invalid reason) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid auth */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale revision / already cancelled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_source_tile_completion: {
        parameters: {
            query?: {
                /** @description Owner or delegated workspace */
                owner_id?: string;
            };
            header?: never;
            path: {
                /** @description SourceTile id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Derived split completion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_source_tile_placements: {
        parameters: {
            query?: {
                /** @description Owner or delegated workspace */
                owner_id?: string;
                /** @description Maximum rows (1..500) */
                limit?: number;
                /** @description Rows to skip */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description SourceTile id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Placements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementTileRead"][];
                };
            };
            /** @description Not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reflow_source_tile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SourceTile id */
                id: string;
            };
            cookie?: never;
        };
        /** @description SourceTile reflow command envelope */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReflowSourceTileRequest"];
            };
        };
        responses: {
            /** @description Command response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Not found or not accessible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Detached / execution / override protects a placement */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tiles: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated list of owner_ids.  Defaults to the authenticated
                 *     owner (= Personal scope) when omitted.
                 */
                owner_ids?: string;
                limit?: number;
                /**
                 * @description View bucketing.  `"by_state"` groups tiles by lifecycle.
                 *     Defaults to `"flat"` (no bucketing) for backwards compat with the
                 *     existing TileSummary-only consumers.
                 */
                view_mode?: string;
                /**
                 * @description Optional lifecycle filter.  One of "ready" | "started" | "done" |
                 *     "closed"; maps to `TileLifecycleKind` numeric constants via
                 *     `parse_view_filters`.
                 */
                lifecycle?: string;
                /**
                 * @description Range string for `by_state` projection (e.g. "7d", "30d").  Only
                 *     used when `view_mode = "by_state"`.
                 */
                range?: string;
                /**
                 * @description Granularity string for `by_state` projection
                 *     (e.g. "no_breaks,min_0m", "important_only").
                 */
                granularity?: string;
                /** @description Free-text search across title / description / labels. */
                search?: string;
                /**
                 * @description When true, exclude tiles whose first upcoming placement is
                 *     strictly after the current instant.
                 */
                exclude_future?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tile list view-model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TileListView"][];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
