/** @vitest-environment jsdom */
import React from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
const callMock = vi.fn();
vi.mock("@/lib/api/endpoints", () => ({ getCoreClient: () => ({ call: callMock }) }));
const wrapper = ({ children }: { children: React.ReactNode }) => React.createElement(QueryClientProvider, { client: new QueryClient({ defaultOptions: { queries: { retry: false } } }) }, children);
describe("usePlacements / useCandidates", () => { beforeEach(() => callMock.mockReset()); it("loads placements", async () => { callMock.mockResolvedValue({ ok: true, data: { placements: [{ id: "p-1", work_tile_id: "w-1", time_tile_id: "t-1", planned_minutes: 30 }] } }); const { usePlacements } = await import("./use-placements"); const { result } = renderHook(() => usePlacements(), { wrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); expect(result.current.placements).toHaveLength(1); }); it("surfaces errors", async () => { callMock.mockResolvedValue({ ok: false, error: { message: "boom" } }); const { usePlacements } = await import("./use-placements"); const { result } = renderHook(() => usePlacements(), { wrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); expect(result.current.error?.message).toBe("boom"); }); it("refreshes", async () => { callMock.mockResolvedValueOnce({ ok: true, data: { placements: [] } }).mockResolvedValueOnce({ ok: true, data: { placements: [{ id: "p-2", work_tile_id: "w-2", time_tile_id: "t-2", planned_minutes: 25 }] } }); const { usePlacements } = await import("./use-placements"); const { result } = renderHook(() => usePlacements(), { wrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); await act(async () => { await result.current.refresh(); }); await waitFor(() => expect(result.current.placements).toHaveLength(1)); }); it("loads candidates", async () => { callMock.mockResolvedValue({ ok: true, data: { candidates: [{ work_tile_id: "w-9" }] } }); const { useCandidates } = await import("./use-placements"); const { result } = renderHook(() => useCandidates(), { wrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); expect(result.current.candidates[0].work_tile_id).toBe("w-9"); }); });
