/** @vitest-environment jsdom */
import React from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
const mockCall = vi.fn();
vi.mock("@/shared/api/endpoints", () => ({ getCoreClient: () => ({ call: mockCall }) }));
const sampleWorkspace = { id: "ws-1", kind: 1, display_name: "Project 1", slug: null, email: null, parent_subject_id: null, color: "#3366ff", owner_user_id: "u-1", disabled_at: null, created_at: "2026-06-29T00:00:00Z", updated_at: "2026-06-29T00:00:00Z" };
const wrapper = ({ children }: { children: React.ReactNode }) => React.createElement(QueryClientProvider, { client: new QueryClient({ defaultOptions: { queries: { retry: false } } }) }, children);
describe("useWorkspaces", () => { beforeEach(() => mockCall.mockReset()); it("loads workspaces on mount", async () => { mockCall.mockResolvedValueOnce({ ok: true, data: { items: [sampleWorkspace], count: 1 } }); const { useWorkspaces } = await import("./use-workspaces"); const { result } = renderHook(() => useWorkspaces(), { wrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); expect(result.current.workspaces[0].display_name).toBe("Project 1"); }); it("surfaces errors", async () => { mockCall.mockResolvedValueOnce({ ok: false, error: { message: "boom" } }); const { useWorkspaces } = await import("./use-workspaces"); const { result } = renderHook(() => useWorkspaces(), { wrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); expect(result.current.error?.message).toBe("boom"); }); it("orders workspaces as a parent-first tree", async () => { const { orderWorkspaceTree } = await import("./use-workspaces"); const tree = orderWorkspaceTree([{ ...sampleWorkspace, id: "child", display_name: "Child", parent_subject_id: "parent" }, { ...sampleWorkspace, id: "parent", display_name: "Parent" }, { ...sampleWorkspace, id: "root", display_name: "Root" }]); expect(tree.map(({ workspace, depth }) => [workspace.id, depth])).toEqual([["parent", 0], ["child", 1], ["root", 0]]); }); it("keeps refresh stable across rerenders", async () => { mockCall.mockResolvedValue({ ok: true, data: { items: [sampleWorkspace], count: 1 } }); const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); const stableWrapper = ({ children }: { children: React.ReactNode }) => React.createElement(QueryClientProvider, { client }, children); const { useWorkspaces } = await import("./use-workspaces"); const { result, rerender } = renderHook(() => useWorkspaces(), { wrapper: stableWrapper }); await waitFor(() => expect(result.current.loading).toBe(false)); const initialRefresh = result.current.refresh; rerender(); expect(result.current.refresh).toBe(initialRefresh); }); it("fires a refresh-keyed effect only once across rerenders", async () => { mockCall.mockResolvedValue({ ok: true, data: { items: [sampleWorkspace], count: 1 } }); const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); const effectWrapper = ({ children }: { children: React.ReactNode }) => React.createElement(QueryClientProvider, { client }, children); const { useWorkspaces } = await import("./use-workspaces"); const callMounts = { current: 0 }; const Consumer = () => { const { refresh } = useWorkspaces(); React.useEffect(() => { callMounts.current += 1; refresh(); }, [refresh]); return null; }; const { rerender } = renderHook(() => Consumer(), { wrapper: effectWrapper }); rerender(); rerender(); await waitFor(() => expect(callMounts.current).toBe(1)); }); });
